global:
  imageRegistry: ""
  imagePullSecrets: []


metricsServer:
  enabled: true

metrics-server:
  fullnameOverride: "metrics-server"

  image:
    registry: docker.io
    repository: kubesphere/metrics-server
    # tag: "v0.8.0"

  args:
  - --kubelet-insecure-tls

  # See https://github.com/kubernetes-sigs/metrics-server#scaling
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi

  addonResizer:
    enabled: false

frontend:
  enabled: true
  image:
    registry: docker.io
    repository: kubesphere/metrics-server-frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "main"  

ks-autoscaling-controller:
  nameOverride: "controller"
  extraArgs:
  - '--enable-hpa'

  image:
    registry: docker.io
    repository: kubesphere/ks-autoscaling-controller
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.1.0-beta.1"

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 64Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
