apiVersion: v2
name: frontend
description: Frontend of metrics-server extension.
type: application
version: 0.3.0
appVersion: "1.1.0"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere

