apiVersion: v2
name: frontend
description: Frontend of metrics-server extension.
type: application
version: 0.2.1
appVersion: "1.0.1"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere

