{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ks-autoscaling-controller.fullname" . }}
  labels:
    {{- include "ks-autoscaling-controller.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ks-autoscaling-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ks-autoscaling-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
